# Event - What starts this workflow?
on: push
  
  
# Name of the workflow
name: on-push-run-only

# Jobs - What the computer should do? 
jobs:
  write-message:
    # Use Ubuntu   
    runs-on: ubuntu-latest 
    steps:
      
      - name: echo command
        run:  echo "it worked!"
      
      - name: Run bash script
        run: bash shell_script.sh

       # Install R
      - uses: r-lib/actions/setup-r@v2    
      - name: print-message   
        # Code to execute R script
        run: Rscript -e 'print("Hello R World!")' 
          